name: Rust

on:
  push:
    branches:
      - master
      - 'feature/**'
  pull_request:
    branches:
      - master
      - 'feature/**'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: find -name Cargo.toml | xargs dirname | xargs -n1 -I{} sh -x -c "cd {} && cargo build --verbose"
    - name: Run tests
      run: find -name Cargo.toml | xargs dirname | xargs -n1 -I{} sh -x -c "cd {} && cargo test --verbose"
